import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className={`min-h-screen `}>
      <Navbar />
      <main className="container mx-auto px-4 py-8 ">{children}</main>
    </body>
  );
}
